name: Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm i
          npm run build
          rm -r /var/www/php/portfolio-react/* || true
          cp -r dist/* /var/www/php/portfolio-react